### ISSUE TITLE
请问支持打包PC加密吗？

### ISSUE THREAD

**Issue by yzx4036** [badApple001/Il2cppEncrtypt#1]
请问支持打包PC加密吗？如果不支持需要如何修改，是否可以提供一个思路？谢谢。

**Comment by badApple001** [comment]
1. 在Unity安装目录下 如: C:\Program Files\Unity\Hub\Editor\2021.3.22f1\Editor\Data\il2cpp\libil2cpp\vm
2. 找到MetadataLoader.cpp文件 
3. 找到插件里的Editor\local下的 vm_MetadataLoader.cpp文件 Copy代码替换掉源MetadataLoader.cpp文件解密部分
4. Unity打包输出PC项目
5. 找到并加密 Buckshot Roulette_Data\il2cpp_data\Metadata下的 global-metadata.dat

**Comment by yzx4036** [comment]
谢谢。
